import Link from "next/link";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="flex w-full p-1 border-b border-blue-600 items-center justify-between">
          <Link href={"/"} className="btn btn-success">
            Logo
          </Link>
          <div className="flex w-fit gap-4 p-5  items-center justify-between">
            <Link href={"/products"} className="btn btn-success">
              products
            </Link>
            <Link href={"/about"} className="btn btn-success">
              about
            </Link>
            <Link href={"/extra"} className="btn btn-success">
              extra
            </Link>
            <Link href={"/api/auth/signout"} className="btn btn-success">
              Signout
            </Link>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
