import Image from "next/image";
import "./globals.css";
import Navbar from "./components/Navbar";
import Profile from "./components/Profile";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <Profile />
        <div className="container">{children}</div>
      </body>
    </html>
  );
}
